### ISSUE TITLE
Time for paper submission

### ISSUE THREAD

**Issue by aqizhoua** [OrigamiSL/OTETrack#3]
Excellent work! I noticed that you cited the work of CVPR2024. When was your paper submitted?Thank you.

**Comment by OrigamiSL** [comment]
Thank you for your concern. The first version of manuscript was submitted to TCSVT in the middle of April 16th, 2024.

**Comment by aqizhoua** [comment]
Your work is amazing and it was received so quickly. Thanks for the quick response.
