### ISSUE TITLE
About causal mask and decoder

### ISSUE THREAD

**Issue by yuyangpoi** [OrigamiSL/OTETrack#5]
The part of self-attention in the TargetQueryDecoderLayer is removed and the causal mask is modified (not been used). 
It is to remove the connection between the four coordinates, and does it have a significant impact on the results?

**Comment by OrigamiSL** [comment]
Yes. The experiments told that it is better to make four coordinate trajectories independent with each other. The idea of auto-regression is not adopted in this work.

**Comment by yuyangpoi** [comment]
Thanks. 
I am curious about how many performance differences there may be. 
Will there be more than two points?

**Comment by OrigamiSL** [comment]
Not much for accuracy. Even smaller than one point. But more efficient without auto-regression.

**Comment by yuyangpoi** [comment]
ok, thanks
